### ISSUE TITLE
export sce from python 

### ISSUE THREAD

**Issue by amoyguang1** [BiocPy/SingleCellExperiment#2]
hello, the package is very cool to convert annadata into sce format. May i ask a question, please? How do i export the sce object to be able to load into R? Thanks a lot.

**Comment by jkanche** [comment]
Currently there's not a straight forward way of doing this. One can read an RDS file using [rds2py](https://github.com/biocpy/rds2py) from R to Python. 

I've been thinking of implementing language agnostic representations for datasets so that they can be read from any language. Hopefully that will come soon. but right now, may be write to H5AD then read it in R?

**Comment by nleroy917** [comment]
Hello!

I have an interest in this... I'm analyzing scATAC-seq data (and lots of it) using [SnapATC2](https://github.com/kaizhang/SnapATAC2). The doublet removal step can be problematic at times (slow and finicky). To that end, I was going to try and "outsource" that step to something like [scDblFinder](https://github.com/plger/scDblFinder), then jump back into SnapATAC2 to finish my processing.

I was going to do this in a few steps:

1. Import `fragment.tsv.gz` files using SnapATAC2 to build `.h5ad` files.
2. Process as normal, **up to doublet detection/removal**.
3. Read `.h5ad` using `SingleCellExperiment` and output into a format compatible with `scDblFinder`.
4. Run doublet detection/removal
5. Export results by barcode (or something to map back)
6. Pull results back into python and attached to my `.h5ad` file/object, filter

I don't know if this even makes sense. I saw [this issue](https://github.com/plger/scDblFinder/issues/116) over in the `scDblFinder` repo, which seems to indicate that maybe this is possible.

Let me know if you have any thoughts here!

Nathan

**Comment by jkanche** [comment]
@nleroy917: An alternative option is to save these objects as [ArtifactDB](https://github.com/ArtifactDB) representations on disk. 

you can use the [dolomite-suite](https://github.com/ArtifactDB/dolomite-base) of packages to store BiocPy objects from Python into a language agnostic format. Then read these objects back in R using the equivalent [alabaster suite](https://github.com/ArtifactDB/alabaster.base) of packages or vice-versa. A draft overview of this process is described here from R -> Python - https://biocpy.github.io/tutorial/chapters/language_agnostic.html, but definitely needs more details. 

So ideally for your usecase
1. Save your SingleCellExperiment (SCE) object from Python using dolomite
2. Read the saved object in R using alabaster
3. Run analytical tools (e.g., scDblFinder) in R
4. Save the processed SCE using alabaster
5. Read the results back in Python using dolomite

Hope this helps!

**Comment by jkanche** [comment]
no worries, feel free to open an issue if you run into any bugs.
