### ISSUE TITLE
Export BaseSE class

### ISSUE THREAD

**Issue by DiDeoxy** [BiocPy/SingleCellExperiment#9]
As it is used to type the `experiment` field a developer needs easy access to it when they want to use type hints.

**Comment by jkanche** [comment]
you should not be using BaseSE. you should explicitly use the user level classes to specify types in your code

**Comment by DiDeoxy** [comment]
Alright, I am back with a better explanation!

The invariance section in this post explains the issue: https://blog.daftcode.pl/covariance-contravariance-and-invariance-the-ultimate-python-guide-8fabc0c24278

But to summarize:

I am trying to something like so:

```python
alt_exps: Dict[str, Union[SummarizedExperiment, SIngleCellExperiment]] = ...

SingleCellExperiment(
    ...,
    altExps=alt_exps,
   ...,
)
```

However, the invariance of `MutableMapping[str, BaseSE]` due to it being mutable causes this to be erroneous because a different derived type of `BaseSE` to the `Union` used could be added to the `MutableMapping` at some point.

Thus I need either `BaseSE` or a `Protocol` exposed for type hinting purposes.

**Comment by DiDeoxy** [comment]
@jkanche FYI

**Comment by jkanche** [comment]
you can do that with `SummarizedExperiment`, at the end of the day everything must extend an SE.
